# This is a basic workflow to help you get started with Actions

name: CI/CD Java Web App

# Controls when the workflow will run
on:  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-webapp.war
          path: '${{ github.workspace }}/target/*.war'
  
  deploy-java-webapp:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [build]
    environment:
      name: PoC-AppService
      url: https://oa-poc-javawebapp.azurewebsites.net

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Download artifact from build job
        id: download
        uses: actions/download-artifact@v3
        with:
          name: java-webapp.war
          path: ${{ github.workspace }}/target
          
      - name: 'Deploy Java WebApp'
        run: | 
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az login --service-principal -u ${{ secrets.CLIENTID }} -p ${{ secrets.CLIENTSECRET }} --tenant ${{ secrets.TENANTID }}
          az webapp deploy --resource-group ${{ secrets.AZURE_RG }} --name oa-poc-javawebapp --src-path ${{ github.workspace }}/target/AirlinesReservationSample-0.0.1-SNAPSHOT.war --type war
    